loader.efi: unused variable 'err'
../env.c: In function 'command_efi_set':
../env.c:917:13: error: unused variable 'err' [-Werror=unused-variable]
  EFI_STATUS err;
             ^~~
../env.c: In function 'command_efi_unset':
../env.c:954:13: error: unused variable 'err' [-Werror=unused-variable]
  EFI_STATUS err;
             ^~~
cc1: all warnings being treated as errors