pci_emul.c: In function 'pci_emul_alloc_pbar': pci_emul.c:591:17: error: 'mask' may be used uninitialized in this function [-Werror=maybe-uninitialized]
This is because gcc doesn't understand that assert(0) never returns;
replace it with abort().