loader: comconsole.c unused variable 'intbuf'
comconsole.c: In function 'comc_pcidev_handle':
comconsole.c:528:7: error: unused variable 'intbuf' [-Werror=unused-variable]
  char intbuf[64];
       ^~~~~~
cc1: all warnings being treated as errors